### ISSUE TITLE
Reprompt shouldn't be able to provide the same option again

### ISSUE THREAD

**Issue by br90218** [bestdtang/KOE-Demo#3]
https://github.com/bestdtang/KOE-Demo/blob/57f562eb54065650891457f9a39e26f73c46654f/Demo_Build/content/story.abc#L411

When you're at the signpost, the script reprompts `the cross` node, which in the end gives three option to the players: the signpost, the mayor's office and the beauty salon.

It doesn't make sense if the player is at the signpost and Alexa is still telling you that you can "go" to the signpost. Same issues persist everywhere in the game. May need to hand pick them out.

**Comment by bestdtang** [comment]
Got Ya
